### ISSUE TITLE
NSSM wont install due to previous version running

### ISSUE THREAD

**Issue by axelrtgs** [dhoer/chef-nssm#14]
Since upgrading to the latest version of the cookbook, it keeps trying to install a newer version of NSSM and since NSSM is currently running it gets an access denied error trying to overwrite the file failing the chef run.

**Comment by axelrtgs** [comment]
since why run isn't supported i was able to fix this by modifying the default recipe and adding a notification on the remote_file resource to kill NSSM. i tried in another wrapper cookbook to subscribe to the resource but it did not work.

**Comment by dhoer** [comment]
Can you please submit a PR with the bug fix? Thanks in advance.

**Comment by axelrtgs** [comment]
its not elegant at all as most would not want to blindly force kill nssm in all cases just like that and potentially cause other issues. im not sure if theres a better solution to it, right now i needed to get it tot work for my use case but i will find some time to make a proper commit with a better solution that covers all use cases. just wanted to document here in case anyone else had ideas.

ideally fixing the whyrun issue in #15 would essentially allow us to kill it ourselves with a notification making this a closed will not resolve issue since fixing whyrun is the best solution.

**Comment by axelrtgs** [comment]
given that whyrun is now supported and its easier to manage the services and kill them ourselves gracefully to allow for overwrites this issue is now irrelevant
