### ISSUE TITLE
NSSM resource doesn't support whyrun

### ISSUE THREAD

**Issue by axelrtgs** [dhoer/chef-nssm#15]
in trying to resolve #14 i added a notification to a resource that would stop services and kill NSSM so it could overwrite but it didn't work because NSSM resource doesn't support why run

**Comment by dhoer** [comment]
Is it related to this bug? https://github.com/chef/chef/issues/4537

**Comment by dhoer** [comment]
Adding the following to provisioner/default.rb might fix it:
```
def whyrun_supported?
    true
end
```

**Comment by dhoer** [comment]
See https://gist.github.com/lamont-granquist/8cda474d6a31fadd3bb3b47a66b0ae78#old-school-lwrps

**Comment by axelrtgs** [comment]
i noticed the first line in the gist:

> use_inline_resources  # you still have to do this, if you don't notifications off of this resource will be broken
> 
> # you have to worry about this
> def whyrun_supported?
>   true
> end

would fixing why run using the workaround work on its own or would we need to use the inline resources thing also?

**Comment by axelrtgs** [comment]
i will try out the fix and let you know how it goes. ill only have some time tomorrow to look at it though and if that works we can close #14 since we can handle that outside the install and let each person decide how to kill things as they require. unless you have a different opinion

**Comment by dhoer** [comment]
The use_inline_resources is already set:
https://github.com/dhoer/chef-nssm/blob/master/providers/default.rb#L3

I think that is why it is causing issues.  Add that method should fix it.

**Comment by dhoer** [comment]
v3.0.2 now supports why run. Please let me know if this fixed this issue.

**Comment by axelrtgs** [comment]
why run is now working perfectly. thanks for the quick fix and sorry for the delay in confirming. i am closing the issue now that its resolved
