### ISSUE TITLE
Version 3.0.1 breaking change & semantic versioning

### ISSUE THREAD

**Issue by Annih** [dhoer/chef-nssm#18]
Hello,

This issue is more a oneshot message than a fixable issue.
Version *3.0.1* changed the way [parameters are escaped](https://github.com/dhoer/chef-nssm/commit/6111971f33ed20bf6446cce3989e7cce78af35cb), this is a small change from #7 but it has several side effects that IMHO should have been catched and described in a "major" release.

Some cookbooks were handling escaping by themselves (johnbellone/consul-cookbook#455), which they have to revert now due to broken behavior.

Again, this is just a one shot discussion message. Feel free to close it whenever you want :)

**Comment by dhoer** [comment]
Thanks for sharing that info. I'm not sure how that got introduced.   I can revert that back, if it is not too late.

**Comment by Annih** [comment]
I'm not sure this is worth reverting.
This is a good change, but it should have been "announced" a bit more clearly :D

**Comment by dhoer** [comment]
Would criteo be interested in adopting this cookbook as well? You have already adopted nexus3.

**Comment by Annih** [comment]
Ahah :D we already have a lot of work currently and still need to publish the new version of the nexus3 cookbook ;)
Let's see later if we can find a way to help you :)

**Comment by Annih** [comment]
Ok I found something interesting the escaping thing I linked is only for the `install_if_missing` action, not for the `install` one. But the PR #7 broke the way parameters are handled in a different way, I think I'll apply the escaping too :)

**Comment by axelrtgs** [comment]
@dhoer the comment you made above about criteo adopting the cookbook, are you looking for a new maintainer?

If so can i volunteer since i have an active interest in maintaining and am part of the sous chefs who maintain many community cookbooks. I can give it a good home there with many from the community working together to help maintain it.

**Comment by dhoer** [comment]
@axelrtgs Yes, I can add you as a collaborator.  What is your account name on Chef Supermarket?
