### ISSUE TITLE
Allow nssm installation to be controlled by an attribute

### ISSUE THREAD

**Issue by poblahblahblah** [dhoer/chef-nssm#28]
Hello,

We're already installing NSSM via a chocolatey package (https://chocolatey.org/packages/nssm) which makes the installation from zip an undesired action. Normally we're able to control this by either setting an attribute override or simply not using the default recipe, but due to https://github.com/dhoer/chef-nssm/blob/master/resources/service.rb#L26 we can't just consume the provider since it will force the install by including the default recipe.

I think the easiest path forward that breaks the least would be to adjust the default recipe to look for an attribute that if set to false will just skip nssm installation all together assuming that installation is being handled elsewhere.

I suppose there's also the other option of allowing the consumer to install via chocolatey package, but I don't like that option as much since it would require a dependency on the `chocolatey` cookbook and broadens the scope of dependencies.

I can get a PR going for this, although I wanted your input on it first.

**Comment by axelrtgs** [comment]
@poblahblahblah I guess you can close this now that its released
