### ISSUE TITLE
params is deprecated

### ISSUE THREAD

**Issue by ajrkerr** [dhoer/chef-nssm#8]
Getting this warning message when using nssm. Looks like `params` will no longer be a valid parameter name for a resource.

``` 
       Deprecated features used!
         Property `params` of resource `nssm` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
```

**Comment by dhoer** [comment]
A PR with `params` renamed to `args` would be welcome!

**Comment by dhoer** [comment]
I wonder if `set` is a valid attribute name...

**Comment by dhoer** [comment]
Or maybe `commands`?

**Comment by ajrkerr** [comment]
Could always spell out parameters too. I'll put together a PR. I'm also looking at solving the idempotency issue in the other ticket as well. 

Love this cookbook btw. Saved my bacon while trying to install consul-template.

**Comment by dhoer** [comment]
Parameters would be fine.  Thanks for the kudos!

**Comment by dhoer** [comment]
Released v3.0.0

**Comment by FreakyDug** [comment]
I can't work out what happened, but this change seems to have gone missing in v3.0.0.

The master version of the resource still has params (https://github.com/dhoer/chef-nssm/blob/master/resources/default.rb#L7) and that's what I'm seeing in the source when I download 3.0.0 from the supermarket.

**Comment by dhoer** [comment]
Looks like merge didn't go so well.

**Comment by dhoer** [comment]
I will try to get this back in

**Comment by dhoer** [comment]
v3.0.1 fixes this
