### ISSUE TITLE
nssm does not install on Windows 2008

### ISSUE THREAD

**Issue by poblahblahblah** [dhoer/chef-nssm#9]
Hello,

By default Windows 2008 R2 ships with Powershell version 2 (according to `$PSVersionTable.PSVersion`). Unfortunately, this version of PS does not support `'System.IO.Compression.FileSystem'`. It doesn't support it until Powershell 4.5 according to a quick google search.

In order for this to work on 2008, I think one decent option is the `expand.exe` binary which appears to be available by default.

I can get a PR going with this change, although my question is whether we should use expand.exe everywhere or just for 2008?

Thoughts beyond that? I realize 2008 is very old at this point so it might not be worth supporting.

**Comment by poblahblahblah** [comment]
blurb of code in question: https://github.com/dhoer/chef-nssm/blob/master/recipes/default.rb#L13-L18

**Comment by dhoer** [comment]
Does using v1.x fix this compatibility issue?  I thought Chef 12 installed a version of powershell, but maybe this isn't using it?

**Comment by axelrtgs** [comment]
i am also experiencing an issue with the powershell bit. the windows cookbook has a zip function built into it. perhaps depending on it for the zip and using that method which should work in either case may work better.
